### PR TITLE
Move SUC -> UD feature conversion to tagger

### PR DESCRIPTION
**Pull request by EmilStenstrom**
This moves UD feature conversion from conll.py to tagger.py. It also makes it easier to writing to intermediate files all the time.

### CODE REVIEW

**Comment by EmilStenstrom** [comment]
Hi! Any chance that you could take a look at this in the coming week?

**Comment by EmilStenstrom** [comment]
That was quick! Thanks :)

**Comment by robertostling** [comment]
Sorry! I was busy at the time and then forgot about it.

**Comment by robertostling** [comment]
Aaron Smith was planning to do some further changes to the SUC->UD conversion heuristics, but I'm not sure when he's done with that. Probably nothing big enough to cause significant conflicts though, even if he started already.

**Comment by EmilStenstrom** [comment]
Since the code has moved location he will likely get a merge conflict. I would instead suggest that he starts from the new code instead: https://github.com/EmilStenstrom/efselab/blob/62a1d860dbdb4ae56eec280a132623ddc986df67/tagger.py#L75

**Pull request merged**
